# Generated by Django 4.0.3 on 2022-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDX', models.BigIntegerField()),
                ('ORDER_ID', models.BigIntegerField(blank=True, null=True)),
                ('MALL_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('ORDER_STATUS', models.CharField(max_length=100)),
                ('scm_status', models.CharField(blank=True, max_length=100, null=True)),
                ('PAY_COST', models.IntegerField()),
                ('ORDER_DATE', models.DateTimeField(blank=True, null=True)),
                ('MALL_PRODUCT_ID', models.BigIntegerField(blank=True, null=True)),
                ('PRODUCT_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('SKU_VALUE', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_quan', models.IntegerField(blank=True, null=True)),
                ('DELIVERY_METHOD_STR', models.CharField(blank=True, max_length=100, null=True)),
                ('DELV_COST', models.IntegerField(blank=True, null=True)),
                ('P_EA', models.IntegerField(blank=True, null=True)),
                ('REG_DATE', models.DateTimeField(blank=True, null=True)),
                ('ORD_CONFIRM_DATE', models.DateTimeField(blank=True, null=True)),
                ('RTN_DT', models.DateTimeField(blank=True, null=True)),
                ('CHNG_DT', models.DateTimeField(blank=True, null=True)),
                ('DELIVERY_CONFIRM_DATE', models.DateTimeField(blank=True, null=True)),
                ('CANCEL_DT', models.DateTimeField(blank=True, null=True)),
                ('DELIVERY_ID', models.IntegerField(blank=True, null=True)),
                ('INVOICE_NO', models.BigIntegerField(blank=True, null=True)),
                ('INV_SEND_MSG', models.CharField(blank=True, max_length=100, null=True)),
                ('INV_SEND_DM', models.DateTimeField(blank=True, null=True)),
                ('USER_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('USER_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('USER_TEL', models.CharField(blank=True, max_length=100, null=True)),
                ('USER_CEL', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVE_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVE_TEL', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVE_CEL', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVE_ZIPCODE', models.IntegerField(blank=True, null=True)),
                ('RECEIVE_ADDR', models.CharField(blank=True, max_length=100, null=True)),
                ('DELV_MSG', models.CharField(blank=True, max_length=100, null=True)),
                ('HOPE_DELV_DATE', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
