# Generated by Django 4.0.3 on 2022-03-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2C', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='DELIVERY_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='HOPE_DELV_DATE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='IDX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='RECEIVE_ZIPCODE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
