# Generated by Django 4.0.3 on 2022-03-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2C', '0002_alter_order_list_delivery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='MALL_PRODUCT_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='ORDER_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
