# Generated by Django 4.0.3 on 2022-03-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2C', '0003_alter_order_list_mall_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='memo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
