# Generated by Django 4.0.3 on 2022-03-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2C', '0004_order_list_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctgr', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('pack1', models.IntegerField()),
                ('fac1', models.IntegerField()),
                ('fac2', models.IntegerField()),
                ('pack2', models.IntegerField()),
            ],
        ),
    ]
