# Generated by Django 4.0.3 on 2022-03-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2C', '0005_category_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
